--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Terpz710/DeathRunes
build-by-default: true
branches:
- main
projects:
  DeathRunes:
    path: ""
    icon: "image.png"
    compressBuilds: bool = true
    excludeDirs:
      [
        "resources"
      ]
    excludeFiles:
      [
        "image.png"
      ]
  lint:
    phpstan: false
...
