build-by-default: true
branches:
  - master
projects:
  DeathRunes:
    path: ""
    icon: "image.png"
    compressBuilds: bool = true
    excludeDirs:
      [
        "resources"
      ]
    excludeFiles:
      [
        "image.png"
      ]